#!/usr/bin/env tsx

/**
 * Migration setup script for multi-schema Prisma setup
 * This script creates initial migrations for both public and store schemas
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const PUBLIC_SCHEMA_DIR = join(__dirname, '../prisma/public');
const STORE_SCHEMA_DIR = join(__dirname, '../prisma/store');

function ensureDirectories() {
  console.log('📁 Ensuring migration directories exist...');
  
  // Create public schema migrations directory
  const publicMigrationsDir = join(PUBLIC_SCHEMA_DIR, 'migrations');
  if (!existsSync(publicMigrationsDir)) {
    mkdirSync(publicMigrationsDir, { recursive: true });
  }
  
  // Create store schema migrations directory
  const storeMigrationsDir = join(STORE_SCHEMA_DIR, 'migrations');
  if (!existsSync(storeMigrationsDir)) {
    mkdirSync(storeMigrationsDir, { recursive: true });
  }
  
  console.log('✅ Migration directories ready');
}

function createMigrationLockFiles() {
  console.log('🔒 Creating migration lock files...');
  
  const publicLockContent = `# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "postgresql"
`;

  const storeLockContent = `# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "postgresql"
`;

  writeFileSync(join(PUBLIC_SCHEMA_DIR, 'migrations/migration_lock.toml'), publicLockContent);
  writeFileSync(join(STORE_SCHEMA_DIR, 'migrations/migration_lock.toml'), storeLockContent);
  
  console.log('✅ Migration lock files created');
}

function main() {
  console.log('🚀 Setting up multi-schema Prisma migrations...\n');
  
  // Ensure directories exist
  ensureDirectories();
  
  // Create migration lock files
  createMigrationLockFiles();
  
  console.log('\n📋 Next steps:');
  console.log('1. Set up your environment variables:');
  console.log('   - DATABASE_URL_PUBLIC=postgresql://user:password@localhost:5432/merchantcore?schema=public');
  console.log('   - DATABASE_URL_STORE=postgresql://user:password@localhost:5432/merchantcore?schema=store_template');
  console.log('   - DATABASE_URL_BASE=postgresql://user:password@localhost:5432/merchantcore');
  console.log('');
  console.log('2. Generate Prisma clients for each schema:');
  console.log('   cd prisma/public && npx prisma generate');
  console.log('   cd prisma/store && npx prisma generate');
  console.log('');
  console.log('3. Create and apply migrations:');
  console.log('   cd prisma/public && npx prisma migrate dev --name init');
  console.log('   cd prisma/store && npx prisma migrate dev --name init');
  console.log('');
  console.log('4. For production deployment:');
  console.log('   cd prisma/public && npx prisma migrate deploy');
  console.log('   cd prisma/store && npx prisma migrate deploy');
  
  console.log('\n✅ Setup script completed!');
}

if (require.main === module) {
  main();
}